### ISSUE TITLE
前端无法播放视频

### ISSUE THREAD

**Issue by sunfeng90** [liebertLEOS/edu#1]
您好，我运行了您的项目。发现前端无法播放视频

**Comment by liebertLEOS** [comment]
1.前端界面的是否正常加载了页面
2.查看视频url是否正常，文件是否存在

**Comment by sunfeng90** [comment]
> 1.前端界面的是否正常加载了页面
> 2.查看视频url是否正常，文件是否存在

我可以加你QQ嘛？我已经申请了，可以通过一下嘛？
界面都加载出来了，接口地址看不到URL。后端配置好了视频了。

**Comment by sunfeng90** [comment]
我的QQ：568202560

**Comment by sunfeng90** [comment]
我发现管理后台无法上传上课资料

**Comment by liebertLEOS** [comment]
后台上传失败，具体报什么错？

**Comment by liebertLEOS** [comment]
qq已经有好多年不用了，你微信

**Comment by sunfeng90** [comment]
fwzkj90
